;///////////////////////////////////////////////////////////////
;// Copyright (c) Varania OS team 2019. All rights reserved.  //
;// Distributed under terms of the GNU General Public License //
;// Task Manager - Менеджер задач                             //
;// Дата: 28.07.2019                                          //
;///////////////////////////////////////////////////////////////

macro tm.init
{
}

macro tm.run_task
{
}

macro tm.close_task
{
}