name: amd64 build and boot

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Получить исходники
        uses: actions/checkout@v7

      - name: Установить QEMU
        run: |
          sudo apt-get update --quiet
          sudo DEBIAN_FRONTEND=noninteractive apt-get install \
            --yes --no-install-recommends qemu-system-x86 seabios

      - name: Собрать и загрузить Varania OS
        run: make test
